OCAMLMAKEFILE = ../OCamlMakefile

SOURCES		= sqlite_util.ml greybottle.ml
PACKS		= plain_config strftime scheduler sqlite3
THREADS		= yes
RESULT		= greybottle

include ../Makefile.global

all: nc

include $(OCAMLMAKEFILE)

